name: Data Export and Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Every hour
permissions:
  contents: write
jobs:
  data-export-and-release:
    runs-on: ubuntu-latest
    env:
      NIGHTLY_URL: https://github.com/URenko/e-hentai-db/releases/download/nightly/e-hentai.db.zstd
      SMMAP_URL: https://github.com/user-attachments/files/24399975/smmap.pickle.gz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - name: Install project dependencies
        run: uv sync
      - name: Download and decompress database
        run: |
          aria2c -x 16 -s 32 "$NIGHTLY_URL" -o e-hentai.db.zstd
          zstd -d -f e-hentai.db.zstd -o e-hentai.db
      - name: Download and decompress smmap.pickle.gz
        run: |
          mkdir -p smmap_get
          curl -L "$SMMAP_URL" -o smmap_get/smmap.pickle.gz
          gzip -dc smmap_get/smmap.pickle.gz > smmap_get/smmap.pickle
      - name: Run data export scripts
        run: |
          uv run step2-export_data.py --first-run
          uv run step3-manual_fix.py
          uv run step2-export_data.py
      - name: Check output files
        run: ls -lh tagname_count.csv.gz tid_count_tag.csv.gz
      - name: Compute Release Tag
        id: tag
        run: echo "tag=v$(date '+%Y.%m.%d')" >> $GITHUB_OUTPUT
      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            tagname_count.csv.gz
            tid_count_tag.csv.gz
